#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.

# Update package index and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure redirection in Nginx
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/in/fortunatus-wulnye/ permanent;" /etc/nginx/sites-enabled/default
# Restart Nginx service
sudo systemctl restart nginx
