#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.

# Update package index and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

echo "
server {
    listen 80;
    server_name 52.201.211.55;

    location /redirect_me {
        return 301 https://www.linkedin.com/in/fortunatus-wulnye/;
    }

    # Add other server block configurations if needed
}
" | tee /etc/nginx/sites-available/redirect.conf


ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default
service nginx restart
