#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.

# Update package index and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

sudo tee /etc/nginx/conf.d/redirect_me.conf <<EOF
server {
    listen 80;
    server_name 52.201.211.55;

    location /redirect_me {
        return 301 https://www.linkedin.com/in/fortunatus-wulnye/;
    }
}
EOF

sudo nginx -t
sudo service nginx restart
