#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page
sudo apt-get update -y
sudo apt-get install -y nginx

sudo tee /usr/share/nginx/html/404.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF

sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo sed -i 's|#location = /404.html {|location = /404.html {\n    root /usr/share/nginx/html;\n    internal;\n}|' /etc/nginx/sites-available/default
sudo sed -i 's|#location = /50x.html {|location = /50x.html {\n    root /usr/share/nginx/html;\n}|' /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart

