#!/usr/bin/env bash
# This script configures Nginx to add a custom header to its HTTP response
# on web-01 and web-02 servers.

# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

# Configure custom HTTP response header
sudo sed -i '/^http {/a \        include /etc/nginx/conf.d/*.conf;' /etc/nginx/nginx.conf
sudo bash -c 'echo -e "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom-header.conf'

sudo systemctl restart nginx
