#!/usr/bin/env bash
# This script configures Nginx to add a custom header to its HTTP response
# on web-01 and web-02 servers.

# Get hostname of current server
var_hostname=$(hostname)

# Define strings to be used for Nginx configuration
ERROR_PAGE="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
HEADER="server {\n\tadd_header X-Served-By $var_hostname;"

# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

# Configure custom HTTP response header
sudo sed -i '/^http {/a \        server_tokens off;\n        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

sudo systemctl restart nginx
