#!/usr/bin/env bash
#The script changes port used by Nginix from 8080 to 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
