#!/usr/bin/env bash
#the Script automates the changes of the port in Nginx config file from 8080 to 80.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default # Replace 8080 with 80 in the config file
sudo service nginx restart  # Restart Nginx service
kill -9 "$(cat /var/run/nginx.pid)"  # Kill Nginx process