#!/usr/bin/env bash
# Author: Fortunatus A. Wulnye
# Infinity loop and sending signal
# trap receive signal
trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
