#!/usr/bin/env bash
# A bash script that creates an RSA key pair

private_key_name="school"
key_bits=4096
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$private_key_name"
